# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Steam activity
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam: yes
          plugin_steam_token: 01886B661FBF4270F8A4A89677A39D15
          plugin_steam_user: "0"
          plugin_steam_achievements_limit: 0
